name: clonepool
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.8
  - tox
  - pytest
  - click
  - networkx
  - numpy
  - tqdm
  - more-itertools
  - r
  - r-readr
  - r-ggplot2
